---
- name: "Build Image and run container with ansible playbook"
  hosts: localhost
  tasks:
  - name: stop running container
    command: docker stop laravel-container
    ignore_errors: true

  - name: remove stopped container
    command: docker rm laravel-container
    ignore_errors: true

# Make sure to change the image name with your personal dockerhub account and reposiroty   
  - name: remove used image
    command: docker rmi wassimkaouia/qrcode_app
    ignore_errors: true

# Make sure to change the image name with your personal dockerhub account and reposiroty 
  - name: build docker image from dockerfile
    command: docker build -t wassimkaouia/qrcode_app .  

# Make sure to change the image name with your personal dockerhub account and reposiroty 
  - name: run c
    command: docker build -t wassimkaouia/qrcode_app .    

# Make sure to change the image name with your personal dockerhub account and reposiroty 
  - name: push image to dockerhub
    command: docker push wassimkaouia/qrcode_app


